const ERROR_BAD_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_INTERNAL_SERVER = 500;
const STATUS_CREATED = 201;
const STATUS_OK = 200;
const UNAUTH_ERR = 401;
const FORBIDDEN_ERR = 403;
const CONFLICT_ERR = 409;

module.exports = {
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  ERROR_INTERNAL_SERVER,
  STATUS_CREATED,
  STATUS_OK,
  UNAUTH_ERR,
  FORBIDDEN_ERR,
  CONFLICT_ERR,
};
